addons:
  postgresql: 9.3

before_script:
  - psql -c 'create database sqlalchemy_utils_test;' -U postgres
  - mysql -e 'create database sqlalchemy_utils_test;'


language: python
python:
  - 2.6
  - 2.7
  - 3.3
  - 3.4

install:
  - pip install -e ".[test]"
script:
  - py.test
